# Generated by Django 3.1.3 on 2021-01-03 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108')], default=101)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('people', models.CharField(choices=[('1 person', '1 person'), ('2 persons', '2 persons'), ('3 persons', '3 persons'), ('4 persons', '4 persons')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=101)),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=12)),
                ('category', models.CharField(choices=[('Suit', 'Suit'), ('Double Bed', 'Double Bed'), ('Single Bed', 'Single Bed'), ('Triple Bed', 'Triple Bed')], max_length=10)),
                ('cost', models.IntegerField(default=2000)),
                ('image', models.ImageField(default='', upload_to='Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Exfd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('FM', 'FeMale')], max_length=10)),
                ('lang', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Urdhu', 'Urdhu')], max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phno', models.CharField(max_length=10, null=True)),
                ('impf', models.ImageField(default='avathar.png', upload_to='Profile/')),
                ('d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
